load("@io_bazel_rules_go//go:def.bzl", "go_test")

def gg_test():
  build_specific_tags = select({
    '//buildsettings:sql_driver_sqlite': ['sqlite'],
    '//buildsettings:sql_driver_postgres': ['postgres'],
  })

  go_test(
    name = 'go_test',
    importpath = 'github.com/Mythra/rules_go_repro/embed/pkg_test',
    srcs = native.glob(['*_test.go']),
    embed = [
      ":autogenerated",
    ],
    cgo = True,
    pure = 'off',
    gotags = build_specific_tags,
    static = 'on',
    size = 'small',
  )

